from __future__ import annotations

from dataclasses import dataclass, field

from ..texto import JANELA_NEGACAO_MODELO, NEGACOES

VERSAO_LEXICO = "lexico-aspectos-v3"

JANELA_NEGACAO = JANELA_NEGACAO_MODELO

__all__ = ["ASPECTOS", "Aspecto", "JANELA_NEGACAO", "NEGACOES", "VERSAO_LEXICO"]


@dataclass(frozen=True, slots=True)
class Aspecto:
    nome: str
    rotulo: str
    positivos: tuple[str, ...] = ()
    negativos: tuple[str, ...] = ()
    neutros: tuple[str, ...] = field(default=())


ASPECTOS: tuple[Aspecto, ...] = (
    Aspecto(
        nome="PONTUALIDADE",
        rotulo="Pontualidade",
        positivos=(
            "pontual",
            "pontualidade",
            "pontualissimo",
            "chegou no horario",
            "chegou na hora",
            "chegou no horario combinado",
            "no horario combinado",
            "no horario marcado",
            "no horario",
            "na hora marcada",
            "dentro do prazo",
            "cumpriu o prazo",
            "cumpriu o horario",
            "chegou cedo",
            "chegou adiantado",
            "chegou antes do horario",
            "entregou no prazo",
            "terminou no prazo",
            "respeitou o horario",
            "sempre no horario",
            "nunca atrasou",
        ),
        negativos=(
            "atrasou",
            "atraso",
            "atrasado",
            "atrasada",
            "chegou tarde",
            "chegou atrasado",
            "fora do prazo",
            "nao cumpriu o prazo",
            "nao cumpriu o horario",
            "nao respeitou o horario",
            "nao apareceu",
            "faltou no dia",
            "faltou sem avisar",
            "remarcou varias vezes",
            "horas de atraso",
            "uma hora de atraso",
            "me deixou esperando",
            "fiquei esperando",
            "esperei muito",
            "perdeu a hora",
            "sempre atrasa",
        ),
        neutros=("horario", "prazo"),
    ),
    Aspecto(
        nome="QUALIDADE",
        rotulo="Qualidade",
        positivos=(
            "otimo trabalho",
            "excelente trabalho",
            "otimo servico",
            "excelente servico",
            "bom trabalho",
            "bom servico",
            "trabalho impecavel",
            "servico impecavel",
            "impecavel",
            "acabamento perfeito",
            "otimo acabamento",
            "ficou perfeito",
            "ficou otimo",
            "ficou excelente",
            "bem feito",
            "benfeito",
            "muito bem feito",
            "caprichoso",
            "capricho",
            "caprichado",
            "trabalho caprichado",
            "trabalho de qualidade",
            "servico de qualidade",
            "qualidade do servico",
            "qualidade do trabalho",
            "alta qualidade",
            "otima qualidade",
            "trabalho bem executado",
            "servico de primeira",
            "otimo resultado",
            "resultado excelente",
            "superou minhas expectativas",
            "superou as expectativas",
            "acima do esperado",
            "nota dez",
        ),
        negativos=(
            "mal feito",
            "malfeito",
            "mal acabado",
            "acabamento ruim",
            "baixa qualidade",
            "pessima qualidade",
            "sem qualidade",
            "precisei refazer",
            "tive que refazer",
            "teve que refazer",
            "tive que chamar outro",
            "chamei outro profissional",
            "servico ruim",
            "trabalho ruim",
            "resultado ruim",
            "ficou ruim",
            "ficou pessimo",
            "ficou torto",
            "pessimo trabalho",
            "pessimo servico",
            "nao terminou o trabalho",
            "nao terminou o servico",
            "deixou pela metade",
            "servico incompleto",
            "trabalho incompleto",
            "danificou",
            "estragou",
            "quebrou",
        ),
        neutros=("qualidade", "acabamento", "resultado"),
    ),
    Aspecto(
        nome="RESOLUCAO",
        rotulo="Resolução",
        positivos=(
            "resolveu meu problema",
            "resolveu o problema",
            "problema resolvido",
            "corrigiu meu problema",
            "corrigiu o problema",
            "resolveu tudo",
            "resolveu na hora",
            "resolveu de primeira",
            "solucionou o problema",
            "solucionou tudo",
            "consertou o problema",
            "consertou tudo",
            "identificou o problema",
            "achou o defeito",
            "deu conta do recado",
        ),
        negativos=(
            "nao resolveu meu problema",
            "nao resolveu o problema",
            "nao resolveu",
            "nao corrigiu meu problema",
            "nao corrigiu o problema",
            "nao corrigiu",
            "nao solucionou",
            "nao consertou",
            "problema nao resolvido",
            "problema continuou",
            "problema voltou",
            "defeito continuou",
            "defeito voltou",
            "continua com problema",
            "continua com defeito",
            "tive que chamar novamente",
            "piorou o problema",
            "nao deu conta",
        ),
        neutros=("problema", "defeito"),
    ),
    Aspecto(
        nome="RAPIDEZ",
        rotulo="Rapidez",
        positivos=(
            "rapido",
            "rapidinho",
            "rapidez",
            "agil",
            "agilidade",
            "resolveu rapido",
            "terminou rapido",
            "fez rapido",
            "eficiente",
            "eficiencia",
            "em pouco tempo",
            "sem enrolacao",
        ),
        negativos=(
            "demorou demais",
            "demorou muito",
            "demorou uma eternidade",
            "demorou",
            "demora",
            "demorado",
            "muito lento",
            "lento",
            "lentidao",
            "levou o dia todo",
            "enrolou muito",
            "enrolou",
            "ficou enrolando",
        ),
        neutros=("duracao",),
    ),
    Aspecto(
        nome="ATENDIMENTO",
        rotulo="Atendimento",
        positivos=(
            "otimo atendimento",
            "excelente atendimento",
            "bom atendimento",
            "muito atencioso",
            "super atencioso",
            "atencioso",
            "atenciosa",
            "educado",
            "educada",
            "muito educado",
            "gentil",
            "gentileza",
            "simpatico",
            "simpatica",
            "simpatia",
            "prestativo",
            "prestativa",
            "cordial",
            "paciente",
            "respeitoso",
            "agradavel",
            "me tratou muito bem",
            "tratou muito bem",
            "atendeu bem",
        ),
        negativos=(
            "pessimo atendimento",
            "mal atendimento",
            "atendimento ruim",
            "mal educado",
            "maleducado",
            "sem educacao",
            "muito grosso",
            "grosseiro",
            "grosseria",
            "rude",
            "antipatico",
            "arrogante",
            "me ignorou",
            "destratou",
            "falta de respeito",
            "desrespeitoso",
            "mal humorado",
        ),
        neutros=("atendimento",),
    ),
    Aspecto(
        nome="ORGANIZACAO",
        rotulo="Organização",
        positivos=(
            "deixou tudo limpo",
            "deixou tudo organizado",
            "deixou o local limpo",
            "deixou limpo",
            "muito organizado",
            "organizado",
            "organizada",
            "organizacao",
            "limpou tudo",
            "limpou depois",
            "recolheu o material",
            "recolheu tudo",
        ),
        negativos=(
            "deixou muita sujeira",
            "deixou sujeira",
            "muita sujeira",
            "sujeira",
            "sujou tudo",
            "deixou tudo sujo",
            "bagunca",
            "bagunceiro",
            "desorganizado",
            "desorganizada",
            "deixou entulho",
            "deixou lixo",
            "nao limpou",
        ),
        neutros=("limpeza",),
    ),
    Aspecto(
        nome="PRECO",
        rotulo="Preço",
        positivos=(
            "preco justo",
            "valor justo",
            "preco acessivel",
            "valor acessivel",
            "preco honesto",
            "preco em conta",
            "otimo custo beneficio",
            "bom custo beneficio",
            "custo beneficio",
            "cobrou o combinado",
            "cobrou o justo",
            "nao cobrou a mais",
            "barato",
            "valeu cada centavo",
        ),
        negativos=(
            "acima do orcamento",
            "cobrou a mais",
            "cobrou alem do combinado",
            "preco alto",
            "preco salgado",
            "preco absurdo",
            "muito caro",
            "caro",
            "carissimo",
            "abusivo",
            "valor abusivo",
            "cobrou muito",
            "cobranca indevida",
            "nao vale o preco",
        ),
        neutros=("preco", "orcamento", "valor cobrado", "valor"),
    ),
    Aspecto(
        nome="COMUNICACAO",
        rotulo="Comunicação",
        positivos=(
            "comunicacao clara",
            "otima comunicacao",
            "boa comunicacao",
            "explicou cada etapa",
            "explicou tudo",
            "explicou direitinho",
            "explicou",
            "tirou todas as duvidas",
            "tirou minhas duvidas",
            "sempre respondeu",
            "respondeu rapido",
            "manteve contato",
            "me manteve informado",
            "avisou antes de chegar",
            "avisou com antecedencia",
            "retorno rapido",
        ),
        negativos=(
            "nao respondeu",
            "nao respondia",
            "nao deu retorno",
            "sem retorno",
            "demorou para responder",
            "dificil de falar",
            "nao avisou",
            "nao explicou nada",
            "nao explicou",
            "comunicacao poderia melhorar",
            "comunicacao ruim",
            "pessima comunicacao",
            "nao atende o telefone",
            "ignorou as mensagens",
            "sumiu do nada",
        ),
        neutros=("comunicacao", "contato", "mensagens"),
    ),
    Aspecto(
        nome="CONFIABILIDADE",
        rotulo="Confiança",
        positivos=(
            "pessoa de confianca",
            "profissional de confianca",
            "muito confiavel",
            "confiavel",
            "honesto",
            "honesta",
            "honestidade",
            "transmite confianca",
            "passa confianca",
            "fiquei tranquilo",
            "sem preocupacao",
        ),
        negativos=(
            "pouco confiavel",
            "nao confiavel",
            "nao inspira confianca",
            "nao passa confianca",
            "desonesto",
            "desonestidade",
            "me enganou",
            "enganou",
            "mentiu",
            "sumiu com o dinheiro",
            "levou minhas coisas",
        ),
        neutros=("confianca",),
    ),
    Aspecto(
        nome="SEGURANCA",
        rotulo="Segurança",
        positivos=(
            "trabalhou com seguranca",
            "trabalho seguro",
            "muito cuidadoso",
            "cuidadoso",
            "tomou todos os cuidados",
            "teve todo o cuidado",
            "usou equipamento de protecao",
            "seguiu as normas de seguranca",
            "protegeu os moveis",
            "cobriu os moveis",
        ),
        negativos=(
            "nao usou equipamento de protecao",
            "sem seguranca",
            "sem nenhum cuidado",
            "nao teve cuidado",
            "nao me senti seguro",
            "deixou fio exposto",
            "risco de acidente",
            "colocou em risco",
            "imprudente",
            "descuidado",
        ),
        neutros=("seguranca", "cuidado"),
    ),
    Aspecto(
        nome="EXPERIENCIA",
        rotulo="Experiência técnica",
        positivos=(
            "profissional experiente",
            "muito experiente",
            "experiente",
            "dominio tecnico",
            "conhecimento tecnico",
            "conhece do assunto",
            "entende do servico",
            "sabe o que faz",
            "especialista",
            "qualificado",
            "profissional qualificado",
            "capacitado",
            "habilidoso",
        ),
        negativos=(
            "inexperiente",
            "sem experiencia",
            "sem preparo",
            "amador",
            "despreparado",
            "nao sabia o que estava fazendo",
            "nao sabe o que faz",
            "nao entende do servico",
            "faltou tecnica",
        ),
        neutros=("experiencia", "tecnica"),
    ),
    Aspecto(
        nome="MATERIAIS",
        rotulo="Materiais e equipamentos",
        positivos=(
            "material de qualidade",
            "material de primeira",
            "otimo material",
            "usou material bom",
            "levou o proprio material",
            "trouxe o material",
            "trouxe as ferramentas",
            "ferramentas adequadas",
            "equipamento adequado",
            "equipamento profissional",
        ),
        negativos=(
            "material de ma qualidade",
            "material ruim",
            "material vagabundo",
            "usou material barato",
            "faltou material",
            "faltou ferramenta",
            "nao trouxe material",
            "nao trouxe as ferramentas",
            "ferramenta inadequada",
            "equipamento improvisado",
        ),
        neutros=("material", "ferramenta", "ferramentas", "equipamento"),
    ),
    Aspecto(
        nome="DISPONIBILIDADE",
        rotulo="Disponibilidade e agenda",
        positivos=(
            "agenda flexivel",
            "flexivel com o horario",
            "flexivel",
            "conseguiu me encaixar",
            "me encaixou na agenda",
            "atendeu no mesmo dia",
            "atendeu de imediato",
            "veio no fim de semana",
            "disponibilidade imediata",
            "sempre disponivel",
            "disponivel",
            "aceitou remarcar",
        ),
        negativos=(
            "dificil de agendar",
            "demorou para agendar",
            "sem disponibilidade",
            "nunca tem horario",
            "agenda lotada",
            "nao consegui marcar",
            "cancelou em cima da hora",
            "desmarcou em cima da hora",
            "cancelou o servico",
        ),
        neutros=("agenda", "agendamento", "disponibilidade"),
    ),
    Aspecto(
        nome="GARANTIA",
        rotulo="Garantia e pós-serviço",
        positivos=(
            "deu garantia",
            "ofereceu garantia",
            "garantia do servico",
            "voltou para revisar",
            "voltou sem cobrar",
            "retornou para ajustar",
            "resolveu na garantia",
            "deu suporte depois",
            "acompanhou depois do servico",
        ),
        negativos=(
            "nao deu garantia",
            "sem garantia",
            "nao honrou a garantia",
            "nao voltou para arrumar",
            "se recusou a voltar",
            "sumiu depois do pagamento",
            "nao atendeu depois do servico",
        ),
        neutros=("garantia", "revisao"),
    ),
    Aspecto(
        nome="TRANSPARENCIA",
        rotulo="Transparência",
        positivos=(
            "orcamento detalhado",
            "orcamento claro",
            "explicou o orcamento",
            "deixou tudo claro",
            "foi transparente",
            "transparente",
            "sem cobranca escondida",
            "sem taxa escondida",
            "sem surpresas",
            "avisou o valor antes",
            "informou o valor antes",
        ),
        negativos=(
            "cobranca escondida",
            "taxa escondida",
            "escondeu custos",
            "nao foi transparente",
            "nao avisou o valor",
            "valor diferente do combinado",
            "mudou o orcamento no final",
            "orcamento enganoso",
            "so avisou depois",
        ),
    ),
    Aspecto(
        nome="CUMPRIMENTO",
        rotulo="Cumprimento do combinado",
        positivos=(
            "fez tudo o que foi combinado",
            "cumpriu tudo o que prometeu",
            "cumpriu o combinado",
            "entregou o que prometeu",
            "fez exatamente o que pedi",
            "seguiu o que foi pedido",
            "nao deixou nada pendente",
        ),
        negativos=(
            "nao fez o que foi combinado",
            "nao cumpriu o combinado",
            "nao cumpriu o que prometeu",
            "fez diferente do combinado",
            "deixou servico pendente",
            "faltou parte do servico",
            "prometeu e nao fez",
            "mudou o combinado",
        ),
        neutros=(
            "cumpriu o que foi contratado",
            "conforme o combinado",
            "conforme contratado",
            "dentro do esperado",
            "combinado",
        ),
    ),
    Aspecto(
        nome="APRESENTACAO",
        rotulo="Postura e apresentação",
        positivos=(
            "bem apresentavel",
            "apresentavel",
            "uniformizado",
            "com uniforme",
            "bem vestido",
            "postura profissional",
            "muito profissional",
            "profissionalismo",
            "discreto",
            "respeitou minha casa",
        ),
        negativos=(
            "mal apresentavel",
            "aparencia descuidada",
            "sem uniforme",
            "sem postura",
            "chegou sujo",
            "cheiro forte",
            "fumou dentro de casa",
            "mexeu nas minhas coisas",
            "ficou no celular",
            "comportamento inadequado",
        ),
        neutros=("postura", "aparencia", "uniforme"),
    ),
    Aspecto(
        nome="RECOMENDACAO",
        rotulo="Recomendação",
        positivos=(
            "recomendo demais",
            "super recomendo",
            "recomendo a todos",
            "recomendo",
            "recomendadissimo",
            "indico a todos",
            "indico",
            "voltarei a contratar",
            "contrataria novamente",
            "vou chamar de novo",
            "chamarei novamente",
            "virou meu profissional fixo",
        ),
        negativos=(
            "nao recomendo",
            "nao indico",
            "nao contrataria novamente",
            "nao chamaria de novo",
            "nunca mais contrato",
            "nunca mais chamo",
            "jamais contrataria",
            "nao vale a pena",
        ),
    ),
)

_POR_NOME = {aspecto.nome: aspecto for aspecto in ASPECTOS}


def rotulo_amigavel(nome_aspecto: str) -> str:
    aspecto = _POR_NOME.get(nome_aspecto)
    return aspecto.rotulo if aspecto else nome_aspecto.capitalize()


def obter_aspecto(nome: str) -> Aspecto | None:
    return _POR_NOME.get(nome)
